#!/bin/bash

set +e
exec 2> /dev/null # remove on debug
function read_reg()
{
    local DATA=$(i2cget -y $1 $2 $(printf "0x%x" $3))
    echo -ne $((DATA))
}
function get_board_info ()
{
    local name
    # Read Board ID from u-boot env
    boardID=`fw_printenv board_id | sed -n "s/^board_id=//p"`
    case $boardID in
       "61"|"64")  # Sunstone board_ids
            name="sunstone"
       ;;
       "63")  # Cinnabar board_ids
            name="cinnabar"
       ;;
       "59"|"62"|"65")  # Shale board_ids
            name="shale"
       ;;
       *)  # Default
            name="sp6"
    esac
    if [ "$1" == "name" ]; then
        echo -ne $name
    fi
    if [ "$1" == "rev" ]; then
        revID=`hexdump -c /sys/bus/i2c/devices/7-0050/eeprom -s 24 -n 1 | head -n 1| awk '{ print $2}'`
        echo -ne $revID
    fi
    if [ "$1" == "id" ]; then
        echo -ne $boardID
    fi
}

function get_hpm_fpga_ver()
{
    local plat
    plat=$(get_board_info name)
    if [ "$plat" == "cinnabar" ] || [ "$plat" == "sunstone" ] || [ "$plat" == "shale" ]; then
        MAJOR=$(read_reg 0 0x50 3)
        MINOR=$(read_reg 0 0x50 4)
        REV=$(printf "\x$(printf %x $(read_reg 0 0x50 5))")
        if [ "$MAJOR" == "0" ] && [ "$MINOR" == "0" ]; then
            echo -ne Unknown
        else
            echo -ne $MAJOR.$MINOR.$REV
        fi
    fi
    if [ "$plat" == "sp6" ]; then
        echo -ne Unknown
    fi
}
# all arguments are function names. invoke directly
if [ ! -z "$1" ] ; then
    $@
fi
