FILESEXTRAPATHS_prepend := "${THISDIR}/linux-aspeed:"

SRC_URI += "file://amd-bmc-baseline.cfg \
            file://0001-drivers-soc-aspeed-Add-MCTP-driver.patch \
            file://0002-drivers-i3c-Modify-I3C-driver.patch \
            file://0003-drivers-soc-aspeed-Add-eSPI-drivers.patch \
            file://0004-drivers-jtag-Add-JTAG-driver.patch \
            file://0005-drivers-soc-Add-uart-DMA-driver.patch \
            file://0006-drivers-soc-aspeed-Add-UART-Routing-driver.patch \
            file://0007-drivers-media-Ignore-known-bogus-interrupts-in-Video.patch \
            file://0008-drivers-hwmon-Add-amd_cpld-and-emc2301-fan-sensor-dr.patch \
            file://0009-drivers-hwmon-Add-tmp468-temperature-sensor-driver.patch \
            file://0010-drivers-mtd-Add-support-for-gigadevice-and-macronix-.patch \
            file://0011-drivers-hwmon-Extend-support-for-infineon-xdpe19283-.patch \
            file://0012-drivers-net-Suppress-warning-message-from-network-dr.patch \
            file://0013-drivers-i2c-Hack-to-restrict-i2c-bus-to-50-KHz-for-l.patch \
            file://0014-linux-aspeed-modify-MP2975-VR-driver-to-support-MP2862-controller.patch \
            file://0015-drivers-misc-Add-APML-SB-TSI-and-SB-RMI-drivers.patch \
            file://0016-ARM-dts-aspeed-Initial-device-tree-for-AMD-Genoa-Pla.patch \
            file://0017-ARM-dts-aspeed-Initial-device-tree-for-AMD-Siena-Pla.patch \
            file://0018-ARM-dts-aspeed-Initial-device-tree-for-AMD-Turin-Pla.patch \
            file://0019-ARM-dts-aspeed-Initial-device-tree-for-AMD-MI-300-Pl.patch \
            file://0020-ARM-dts-aspeed-Add-UART-routing-to-Turin.patch \
            file://0021-drivers-hwmon-add-aspeed-chassis-driver.patch \
            file://0022-ARM-dts-aspeed-Initial-device-tree-for-Galena-Recluse.patch \
            file://0023-ARM-dts-aspeed-initial-Huambo-DTS-file-for-AMD-Turin.patch \
            file://0024-drivers-hwmon-Add-nct7362-fan-controller-driver.patch \
            file://0025-ARM-dts-aspeed-Add-new-HWMON-for-Turin-Lenovo.patch \
            file://0026-ARM-dts-aspeed-Add-UART-routing-to-sh5.patch \
            file://0027-drivers-hwmon-modify-nct7362-driver-for-setting-default-pwm.patch \
            file://0028-ARM-dts-aspeed-modify-Volcano-device-tree-for-VR-device-id.patch \
            file://0029-linux-aspeed-modify-sh5d807-device-tree-for-VR-sensors.patch \
            file://0030-linux-aspeed-driver-Modify-disable-watchdog-timer-in-nct7362.patch \
            file://0031-ARM-dts-aspeed-Initial-device-tree-for-AMD-G304-Plat.patch \
            file://0032-ARM-dts-aspeed-Add-Volcano-sensors.patch \
            file://0033-ARM-dts-aspeed-APML-over-I2C.patch \
            file://0035-ARM-dts-aspeed-Add-Turin-Lenovo-UBM.patch \
            file://0036-ARM-dts-aspeed-Turin-APML-over-i2c-i3c-DTS-changes.patch \
            file://0037-ARM-dts-aspeed-SP5-APML-over-i2c-i3c.patch \
            file://0038-linux-aspeed-driver-i2c-Add-i2c-slave-backend-driver.patch \
            file://0039-apml_sbrmi-Wait-for-fops-to-complete-cleanly-on-devi.patch \
            file://0040-Add-TDA-voltage-regulators-to-dts.patch \
            file://0041-ARM-dts-aspeed-Modify-Genoa-device-trees-for-i2c-slave.patch \
            file://0042-Add-LM95234-to-dts-file.patch \
            file://0043-ARM-dts-aspeed-Add-Riser-PSU-FP-sensors-to-Turin-Lenovo.patch \
            file://0044-ARM-dts-Add-Thermtrip-RSMRST-i3c-at-6MHz-DIMM-Ch1-to-Turin.patch \
            file://0045-ARM-dts-aspeed-Enable-eSPI-UART-and-COM-port.patch \
            file://0046-ARM-dts-aspeed-Enable-eSPI-UART-and-COM-port-for-Tur.patch \
            file://0047-ARM-DTS-Aspeed-Modify-I3c-and-UDC-device-node-enable-with-G304.patch \
            file://0048-Added-Aspeed-BMC-device-drivers-from-Aspeed-Tech-ups.patch \
            file://0049-Enabled-BMC-device-and-configuration-for-SP5-and-SP6.patch \
            file://0050-ARM-dts-aspeed-MP2857-VR-Purico-dts-file-for-AMD-Turin.patch \
            file://0051-drivers-hwmon-Add-mp2857-vr-driver.patch \
            file://0052-linux-aspeed-driver-Add-aspeed_udc-driver-for-BMC-USB-Device.patch \
            file://0053-ARM-DTS-aspped-Add-usb-device-node-for-G304-platfom.patch \
            file://0054-ARM-DTS-aspeed-Modify-g304-dts-for-SPI2-Single-mode.patch \
            file://0055-apml_sbrmi-Use-API-provided-by-linux-to-set-and-clea.patch \
            file://0056-apml_sbrmi-Add-New-member-sock_num-to-the-rmi-device.patch \
            file://0057-apml_sbrmi-Add-support-to-identify-register-address-.patch \
            file://0058-sbrmi-Implement-CPUID-and-MCAMSR-protocol-for-rev-0x.patch \
            file://0059-drivers-jtag-Add-support-for-hardware-mode-2.patch \
            file://0060-linux-aspeed-change-DIMM-i3c-freq-to-2-MHz.patch \
            file://0061-ARM-dts-aspeed-Add-eSPI-peripheral-and-flash-channel.patch \
            file://0062-DTS-changes-to-map-GPIO-line-P0_PRESENT_L-and-P1_PRE.patch \
            file://0063-ARM-dts-aspeed-Enabled-BMC-device-for-I3c-DTS-file.patch \
            file://0064-drivers-soc-aspeed-Increased-DMA-buffer-size.patch \
            file://0065-ARM-dts-aspeed-Add-Turin-U3-i2c-buses.patch \
            file://0066-recipes-kernel-linux-Add-support-for-Winbond-w25q01j.patch \
            file://0067-Add-MPS-driver-for-Purico-VR-in-dts.patch \
            file://0068-Add-MP2857-VR-driver.patch \
            file://0069-linux-speed-Remove-debug-prints-from-i3c-driver.patch \
            file://0070-arm-dts-aspeed-enable-safs-mix-mode.patch \
            file://0071-recipes-kernel-Enable-i2c-slave-backend-device.patch \
            file://0072-Remove-VR-at-slave-address-0x60-for-chalupa-platform.patch \
            file://0073-arm-dts-aspeed-modify-sh5-device-tree-for-VRs-DIMM-and-adc.patch \
            file://0074-Add-TDA-VR-devices-to-dts-for-turin.patch \
            file://0075-drivers-mtd-spi-Add-support-for-GD55-SPI.patch \
            file://0076-ARM-dts-aspeed-Add-Turin-FP-ID-Button-to-GPIO.patch \
            file://0077-Add-sic458-VR-driver.patch \
            file://0078-Add-sic458-driver-for-Purico-VR-in-dts.patch \
            file://0079-Replace-i2c-address-with-pmbus-address-for-TDA-VR.patch \
            file://0080-drivers-soc-Modify-aspeed-bmc-dev-driver-read-to-wak.patch \
            file://0081-ARM-dts-aspeed-Turin-Add-MON_RSMRST_L-line-to-GPIO-G.patch \
            file://0082-Map-RSMRST-GPIO-line-for-Genoa-legacy-boards.patch \
            file://0083-ARM-dts-aspeed-Genoa-Add-MON_RSMRST_L-to-GPIO-G7.patch \
            file://0084-linux-aspeed-port-new-i3c-driver-from-aspeed-repo.patch \
            file://0085-linux-aspeed-dts-changes-for-new-i3c-driver.patch \
            file://0086-drivers-mtd-Add-support-for-Gigadevice-GD25LB-series.patch \
            file://0087-recipes-kernel-linux-linux-aspeed-SPDM-driver-update.patch \
            "
